/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/flug/flug-edit/flug-edit.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '../../../../app/flug/services/flug.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '@angular/forms/src/directives/default_value_accessor';
import * as import14 from '@angular/forms/src/directives/ng_model';
import * as import15 from '@angular/forms/src/directives/ng_control_status';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/forms/src/directives/control_value_accessor';
import * as import19 from '@angular/forms/src/directives/ng_control';
var renderType_FlugEditComponent_Host:import0.RenderComponentType = (null as any);
class _View_FlugEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FlugEditComponent_0_4:import3.FlugEditComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugEditComponent_Host0,renderType_FlugEditComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FlugEditComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FlugEditComponent_0_4 = new import3.FlugEditComponent(this.parentInjector.get(import8.ActivatedRoute),this.parentInjector.get(import9.FlugService));
    this._appEl_0.initComponent(this._FlugEditComponent_0_4,[],compView_0);
    compView_0.create(this._FlugEditComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FlugEditComponent) && (0 === requestNodeIndex))) { return this._FlugEditComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FlugEditComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_FlugEditComponent_Host === (null as any))) { (renderType_FlugEditComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_FlugEditComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const FlugEditComponentNgFactory:import11.ComponentFactory<import3.FlugEditComponent> = new import11.ComponentFactory<import3.FlugEditComponent>('ng-component',viewFactory_FlugEditComponent_Host0,import3.FlugEditComponent);
const styles_FlugEditComponent:any[] = [];
var renderType_FlugEditComponent:import0.RenderComponentType = (null as any);
class _View_FlugEditComponent0 extends import1.AppView<import3.FlugEditComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import12.NgIf;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_10_4:any[];
  _NgModel_10_5:import14.NgModel;
  _NgControl_10_6:any;
  _NgControlStatus_10_7:import15.NgControlStatus;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _DefaultValueAccessor_21_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_21_4:any[];
  _NgModel_21_5:import14.NgModel;
  _NgControl_21_6:any;
  _NgControlStatus_21_7:import15.NgControlStatus;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _DefaultValueAccessor_29_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_29_4:any[];
  _NgModel_29_5:import14.NgModel;
  _NgControl_29_6:any;
  _NgControlStatus_29_7:import15.NgControlStatus;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _DefaultValueAccessor_37_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_37_4:any[];
  _NgModel_37_5:import14.NgModel;
  _NgControl_37_6:any;
  _NgControlStatus_37_7:import15.NgControlStatus;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugEditComponent0,renderType_FlugEditComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'FlugEdit',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_3 = new import2.AppElement(3,(null as any),this,this._anchor_3);
    this._TemplateRef_3_5 = new import16.TemplateRef_(this._appEl_3,viewFactory_FlugEditComponent1);
    this._NgIf_3_6 = new import12.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_5 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','form-group');
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'label',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Id',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'input',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','form-control');
    this._DefaultValueAccessor_10_3 = new import13.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_10));
    this._NG_VALUE_ACCESSOR_10_4 = [this._DefaultValueAccessor_10_3];
    this._NgModel_10_5 = new import14.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_10_4);
    this._NgControl_10_6 = this._NgModel_10_5;
    this._NgControlStatus_10_7 = new import15.NgControlStatus(this._NgControl_10_6);
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_5,'div',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Leere Id oder 0 für neuen Datensatz',(null as any));
    this._text_14 = this.renderer.createText(this._el_5,'\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-group');
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'label',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Von',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_16,'input',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','form-control');
    this._DefaultValueAccessor_21_3 = new import13.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_21));
    this._NG_VALUE_ACCESSOR_21_4 = [this._DefaultValueAccessor_21_3];
    this._NgModel_21_5 = new import14.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_21_4);
    this._NgControl_21_6 = this._NgModel_21_5;
    this._NgControlStatus_21_7 = new import15.NgControlStatus(this._NgControl_21_6);
    this._text_22 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_24 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','form-group');
    this._text_25 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'label',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Von',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_24,'input',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-control');
    this._DefaultValueAccessor_29_3 = new import13.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_29));
    this._NG_VALUE_ACCESSOR_29_4 = [this._DefaultValueAccessor_29_3];
    this._NgModel_29_5 = new import14.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_29_4);
    this._NgControl_29_6 = this._NgModel_29_5;
    this._NgControlStatus_29_7 = new import15.NgControlStatus(this._NgControl_29_6);
    this._text_30 = this.renderer.createText(this._el_24,'\n',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_32 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','form-group');
    this._text_33 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'label',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Datum',(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_32,'input',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','form-control');
    this._DefaultValueAccessor_37_3 = new import13.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_37));
    this._NG_VALUE_ACCESSOR_37_4 = [this._DefaultValueAccessor_37_3];
    this._NgModel_37_5 = new import14.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_37_4);
    this._NgControl_37_6 = this._NgModel_37_5;
    this._NgControlStatus_37_7 = new import15.NgControlStatus(this._NgControl_37_6);
    this._text_38 = this.renderer.createText(this._el_32,'\n',(null as any));
    this._text_39 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_40 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','form-group');
    this._text_41 = this.renderer.createText(this._el_40,'\n    ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'button',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','btn btn-primary');
    this._text_43 = this.renderer.createText(this._el_42,'Speichern',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_10,'ngModelChange',this.eventHandler(this._handle_ngModelChange_10_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_10,'input',this.eventHandler(this._handle_input_10_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_10,'blur',this.eventHandler(this._handle_blur_10_2.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_10_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_10_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_21,'ngModelChange',this.eventHandler(this._handle_ngModelChange_21_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_21,'input',this.eventHandler(this._handle_input_21_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_21,'blur',this.eventHandler(this._handle_blur_21_2.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_21_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_21_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_29,'ngModelChange',this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_29,'input',this.eventHandler(this._handle_input_29_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_29,'blur',this.eventHandler(this._handle_blur_29_2.bind(this)));
    this._expr_24 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_29_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_37,'ngModelChange',this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_37,'input',this.eventHandler(this._handle_input_37_1.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_37,'blur',this.eventHandler(this._handle_blur_37_2.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    const subscription_3:any = this._NgModel_37_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import12.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    if (((token === import13.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_4; }
    if (((token === import14.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_5; }
    if (((token === import19.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_6; }
    if (((token === import15.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_7; }
    if (((token === import13.DefaultValueAccessor) && (21 === requestNodeIndex))) { return this._DefaultValueAccessor_21_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (21 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_21_4; }
    if (((token === import14.NgModel) && (21 === requestNodeIndex))) { return this._NgModel_21_5; }
    if (((token === import19.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_6; }
    if (((token === import15.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_7; }
    if (((token === import13.DefaultValueAccessor) && (29 === requestNodeIndex))) { return this._DefaultValueAccessor_29_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (29 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_29_4; }
    if (((token === import14.NgModel) && (29 === requestNodeIndex))) { return this._NgModel_29_5; }
    if (((token === import19.NgControl) && (29 === requestNodeIndex))) { return this._NgControl_29_6; }
    if (((token === import15.NgControlStatus) && (29 === requestNodeIndex))) { return this._NgControlStatus_29_7; }
    if (((token === import13.DefaultValueAccessor) && (37 === requestNodeIndex))) { return this._DefaultValueAccessor_37_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (37 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_37_4; }
    if (((token === import14.NgModel) && (37 === requestNodeIndex))) { return this._NgModel_37_5; }
    if (((token === import19.NgControl) && (37 === requestNodeIndex))) { return this._NgControl_37_6; }
    if (((token === import15.NgControlStatus) && (37 === requestNodeIndex))) { return this._NgControlStatus_37_7; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = this.context.message;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_3_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    changes = (null as any);
    const currVal_4:any = this.context.flug.id;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgModel_10_5.model = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgModel_10_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_14:any = this.context.flug.abflugort;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_21_5.model = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._NgModel_21_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_24:any = this.context.flug.zielort;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgModel_29_5.model = currVal_24;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_24,currVal_24);
      this._expr_24 = currVal_24;
    }
    if ((changes !== (null as any))) { this._NgModel_29_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_34:any = this.context.flug.datum;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._NgModel_37_5.model = currVal_34;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_34,currVal_34);
      this._expr_34 = currVal_34;
    }
    if ((changes !== (null as any))) { this._NgModel_37_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_5:any = this._NgControlStatus_10_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_10,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_10_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_10,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_10_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_10,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_10_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_10,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_10_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_10,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_10_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_10,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_15:any = this._NgControlStatus_21_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_21,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_21_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_21,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_21_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_21,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_21_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_21,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_21_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_21,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_21_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_21,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_25:any = this._NgControlStatus_29_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_29,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_29_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_29,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_29_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_29,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_29_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_29,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_29_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_29,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_29_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_29,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_35:any = this._NgControlStatus_37_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_37,'ng-untouched',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_37_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_37,'ng-touched',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_37_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_37,'ng-pristine',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_37_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_37,'ng-dirty',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_37_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_37,'ng-valid',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_37_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_37,'ng-invalid',currVal_40);
      this._expr_40 = currVal_40;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_10_5.ngOnDestroy();
    this._NgModel_21_5.ngOnDestroy();
    this._NgModel_29_5.ngOnDestroy();
    this._NgModel_37_5.ngOnDestroy();
  }
  private _handle_ngModelChange_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.flug.id = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_10_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_10_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.flug.abflugort = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_21_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_21_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_21_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_21_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.flug.zielort = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_29_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_29_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_29_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_29_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.flug.datum = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_37_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_37_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_37_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_37_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.save()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_FlugEditComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.FlugEditComponent> {
  if ((renderType_FlugEditComponent === (null as any))) { (renderType_FlugEditComponent = viewUtils.createRenderComponentType('c:/Users/Manfred/Documents/artikel/Blog/angular2-aot/aot/app/flug/flug-edit/flug-edit.component.html',0,import10.ViewEncapsulation.None,styles_FlugEditComponent,{})); }
  return new _View_FlugEditComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_FlugEditComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugEditComponent1,renderType_FlugEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','color:red; font-weight: bold');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n    ',this.parent.context.message,'\n');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FlugEditComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugEditComponent1(viewUtils,parentInjector,declarationEl);
}