/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '../../app/flug/flug.module';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/core/src/application_init';
import * as import12 from '@angular/core/src/testability/testability';
import * as import13 from '@angular/core/src/application_ref';
import * as import14 from '@angular/core/src/linker/compiler';
import * as import15 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import16 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import17 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import18 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/view_utils';
import * as import21 from '@angular/platform-browser/src/browser/title';
import * as import22 from '@angular/http/src/backends/browser_xhr';
import * as import23 from '@angular/http/src/base_response_options';
import * as import24 from '@angular/http/src/backends/xhr_backend';
import * as import25 from '@angular/http/src/base_request_options';
import * as import26 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import27 from '../../app/flug/services/flug.service';
import * as import28 from '@angular/common/src/location/location';
import * as import29 from '@angular/router/src/url_tree';
import * as import30 from '@angular/router/src/router_outlet_map';
import * as import31 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import32 from '@angular/core/src/di/injector';
import * as import33 from './flug/flug-buchen/flug-buchen.component.ngfactory';
import * as import34 from './flug/flug-suchen/flug-suchen.component.ngfactory';
import * as import35 from './flug/passagier-suchen/passagier.suchen.component.ngfactory';
import * as import36 from './flug/flug-edit/flug-edit.component.ngfactory';
import * as import37 from './home/home.component.ngfactory';
import * as import38 from './app.component.ngfactory';
import * as import39 from '@angular/core/src/application_tokens';
import * as import40 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import41 from '@angular/platform-browser/src/dom/events/key_events';
import * as import42 from '@angular/core/src/zone/ng_zone';
import * as import43 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import44 from '../../app/flug/flug-buchen/flug-buchen.component';
import * as import45 from '../../app/flug/flug-suchen/flug-suchen.component';
import * as import46 from '../../app/flug/passagier-suchen/passagier.suchen.component';
import * as import47 from '../../app/flug/flug-edit/flug-edit.component';
import * as import48 from '../../app/home/home.component';
import * as import49 from '@angular/common/src/location/platform_location';
import * as import50 from '@angular/common/src/location/location_strategy';
import * as import51 from '@angular/router/src/router';
import * as import52 from '@angular/core/src/console';
import * as import53 from '@angular/core/src/i18n/tokens';
import * as import54 from '@angular/core/src/error_handler';
import * as import55 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import56 from '@angular/platform-browser/src/dom/animation_driver';
import * as import57 from '@angular/core/src/render/api';
import * as import58 from '@angular/core/src/security';
import * as import59 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import60 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import61 from '@angular/http/src/interfaces';
import * as import62 from '@angular/http/src/http';
import * as import63 from '@angular/router/src/router_config_loader';
import * as import64 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import65 from '@angular/router/src/router_state';
import * as import66 from '@angular/core/src/i18n/tokens';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _ROUTER_FORROOT_GUARD_6:any;
  _RouterModule_7:import8.RouterModule;
  _FlugModule_8:import9.FlugModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import10.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _ApplicationInitStatus_13:import11.ApplicationInitStatus;
  _Testability_14:import12.Testability;
  _ApplicationRef__15:import13.ApplicationRef_;
  __ApplicationRef_16:any;
  __Compiler_17:import14.Compiler;
  __APP_ID_18:any;
  __DOCUMENT_19:any;
  __HAMMER_GESTURE_CONFIG_20:import15.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import16.EventManager;
  __DomSharedStylesHost_23:import17.DomSharedStylesHost;
  __AnimationDriver_24:any;
  __DomRootRenderer_25:import18.DomRootRenderer_;
  __RootRenderer_26:any;
  __DomSanitizer_27:import19.DomSanitizerImpl;
  __Sanitizer_28:any;
  __ViewUtils_29:import20.ViewUtils;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __SharedStylesHost_32:any;
  __Title_33:import21.Title;
  __BrowserXhr_34:import22.BrowserXhr;
  __ResponseOptions_35:import23.BaseResponseOptions;
  __XSRFStrategy_36:any;
  __XHRBackend_37:import24.XHRBackend;
  __RequestOptions_38:import25.BaseRequestOptions;
  __Http_39:any;
  __RadioControlRegistry_40:import26.RadioControlRegistry;
  __ROUTES_41:any[];
  __FlugService_42:import27.FlugService;
  __ROUTER_CONFIGURATION_43:any;
  __LocationStrategy_44:any;
  __Location_45:import28.Location;
  __UrlSerializer_46:import29.DefaultUrlSerializer;
  __RouterOutletMap_47:import30.RouterOutletMap;
  __NgModuleFactoryLoader_48:import31.SystemJsNgModuleLoader;
  __Router_49:any;
  __ActivatedRoute_50:any;
  __APP_BOOTSTRAP_LISTENER_51:any[];
  __TRANSLATIONS_FORMAT_52:any;
  constructor(parent:import32.Injector) {
    super(parent,[
      import33.FlugBuchenComponentNgFactory,
      import34.FlugSuchenComponentNgFactory,
      import35.PassagierSuchenComponentNgFactory,
      import36.FlugEditComponentNgFactory,
      import37.HomeComponentNgFactory,
      import38.AppComponentNgFactory
    ]
    ,[import38.AppComponentNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == (null as any))) { (this.__LOCALE_ID_10 = 'en-US'); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import10.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_16():any {
    if ((this.__ApplicationRef_16 == (null as any))) { (this.__ApplicationRef_16 = this._ApplicationRef__15); }
    return this.__ApplicationRef_16;
  }
  get _Compiler_17():import14.Compiler {
    if ((this.__Compiler_17 == (null as any))) { (this.__Compiler_17 = new import14.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == (null as any))) { (this.__APP_ID_18 = import39._appIdRandomProviderFactory()); }
    return this.__APP_ID_18;
  }
  get _DOCUMENT_19():any {
    if ((this.__DOCUMENT_19 == (null as any))) { (this.__DOCUMENT_19 = import4._document()); }
    return this.__DOCUMENT_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import15.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_20 = new import15.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import40.DomEventsPlugin(),
      new import41.KeyEventsPlugin(),
      new import15.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import16.EventManager {
    if ((this.__EventManager_22 == (null as any))) { (this.__EventManager_22 = new import16.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import42.NgZone))); }
    return this.__EventManager_22;
  }
  get _DomSharedStylesHost_23():import17.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_23 == (null as any))) { (this.__DomSharedStylesHost_23 = new import17.DomSharedStylesHost(this._DOCUMENT_19)); }
    return this.__DomSharedStylesHost_23;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == (null as any))) { (this.__AnimationDriver_24 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_24;
  }
  get _DomRootRenderer_25():import18.DomRootRenderer_ {
    if ((this.__DomRootRenderer_25 == (null as any))) { (this.__DomRootRenderer_25 = new import18.DomRootRenderer_(this._DOCUMENT_19,this._EventManager_22,this._DomSharedStylesHost_23,this._AnimationDriver_24)); }
    return this.__DomRootRenderer_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == (null as any))) { (this.__RootRenderer_26 = import43._createConditionalRootRenderer(this._DomRootRenderer_25,this.parent.get(import43.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import19.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == (null as any))) { (this.__DomSanitizer_27 = new import19.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == (null as any))) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _ViewUtils_29():import20.ViewUtils {
    if ((this.__ViewUtils_29 == (null as any))) { (this.__ViewUtils_29 = new import20.ViewUtils(this._RootRenderer_26,this._APP_ID_18,this._Sanitizer_28)); }
    return this.__ViewUtils_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == (null as any))) { (this.__IterableDiffers_30 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == (null as any))) { (this.__KeyValueDiffers_31 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_31;
  }
  get _SharedStylesHost_32():any {
    if ((this.__SharedStylesHost_32 == (null as any))) { (this.__SharedStylesHost_32 = this._DomSharedStylesHost_23); }
    return this.__SharedStylesHost_32;
  }
  get _Title_33():import21.Title {
    if ((this.__Title_33 == (null as any))) { (this.__Title_33 = new import21.Title()); }
    return this.__Title_33;
  }
  get _BrowserXhr_34():import22.BrowserXhr {
    if ((this.__BrowserXhr_34 == (null as any))) { (this.__BrowserXhr_34 = new import22.BrowserXhr()); }
    return this.__BrowserXhr_34;
  }
  get _ResponseOptions_35():import23.BaseResponseOptions {
    if ((this.__ResponseOptions_35 == (null as any))) { (this.__ResponseOptions_35 = new import23.BaseResponseOptions()); }
    return this.__ResponseOptions_35;
  }
  get _XSRFStrategy_36():any {
    if ((this.__XSRFStrategy_36 == (null as any))) { (this.__XSRFStrategy_36 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_36;
  }
  get _XHRBackend_37():import24.XHRBackend {
    if ((this.__XHRBackend_37 == (null as any))) { (this.__XHRBackend_37 = new import24.XHRBackend(this._BrowserXhr_34,this._ResponseOptions_35,this._XSRFStrategy_36)); }
    return this.__XHRBackend_37;
  }
  get _RequestOptions_38():import25.BaseRequestOptions {
    if ((this.__RequestOptions_38 == (null as any))) { (this.__RequestOptions_38 = new import25.BaseRequestOptions()); }
    return this.__RequestOptions_38;
  }
  get _Http_39():any {
    if ((this.__Http_39 == (null as any))) { (this.__Http_39 = import5.httpFactory(this._XHRBackend_37,this._RequestOptions_38)); }
    return this.__Http_39;
  }
  get _RadioControlRegistry_40():import26.RadioControlRegistry {
    if ((this.__RadioControlRegistry_40 == (null as any))) { (this.__RadioControlRegistry_40 = new import26.RadioControlRegistry()); }
    return this.__RadioControlRegistry_40;
  }
  get _ROUTES_41():any[] {
    if ((this.__ROUTES_41 == (null as any))) { (this.__ROUTES_41 = [
        [{
          path: 'flug-buchen',
          component: import44.FlugBuchenComponent,
          children: [
            {
              path: 'flug-suchen',
              component: import45.FlugSuchenComponent
            }
            ,
            {
              path: 'passagier-suchen',
              component: import46.PassagierSuchenComponent
            }
            ,
            {
              path: 'flug-edit/:id',
              component: import47.FlugEditComponent
            }

          ]

        }
      ],
      [
        {
          path: '',
          redirectTo: 'home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'home',
          component: import48.HomeComponent
        }
        ,
        {
          path: 'flug-buchen',
          loadChildren: 'app/flug/flug.module#FlugModule'
        }
        ,
        {
          path: '**',
          redirectTo: 'home'
        }

      ]

    ]
    ); }
    return this.__ROUTES_41;
  }
  get _FlugService_42():import27.FlugService {
    if ((this.__FlugService_42 == (null as any))) { (this.__FlugService_42 = new import27.FlugService(this._Http_39)); }
    return this.__FlugService_42;
  }
  get _ROUTER_CONFIGURATION_43():any {
    if ((this.__ROUTER_CONFIGURATION_43 == (null as any))) { (this.__ROUTER_CONFIGURATION_43 = {}); }
    return this.__ROUTER_CONFIGURATION_43;
  }
  get _LocationStrategy_44():any {
    if ((this.__LocationStrategy_44 == (null as any))) { (this.__LocationStrategy_44 = import8.provideLocationStrategy(this.parent.get(import49.PlatformLocation),this.parent.get(import50.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_43)); }
    return this.__LocationStrategy_44;
  }
  get _Location_45():import28.Location {
    if ((this.__Location_45 == (null as any))) { (this.__Location_45 = new import28.Location(this._LocationStrategy_44)); }
    return this.__Location_45;
  }
  get _UrlSerializer_46():import29.DefaultUrlSerializer {
    if ((this.__UrlSerializer_46 == (null as any))) { (this.__UrlSerializer_46 = new import29.DefaultUrlSerializer()); }
    return this.__UrlSerializer_46;
  }
  get _RouterOutletMap_47():import30.RouterOutletMap {
    if ((this.__RouterOutletMap_47 == (null as any))) { (this.__RouterOutletMap_47 = new import30.RouterOutletMap()); }
    return this.__RouterOutletMap_47;
  }
  get _NgModuleFactoryLoader_48():import31.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_48 == (null as any))) { (this.__NgModuleFactoryLoader_48 = new import31.SystemJsNgModuleLoader(this._Compiler_17,this.parent.get(import31.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_48;
  }
  get _Router_49():any {
    if ((this.__Router_49 == (null as any))) { (this.__Router_49 = import8.setupRouter(this._ApplicationRef_16,this._UrlSerializer_46,this._RouterOutletMap_47,this._Location_45,this,this._NgModuleFactoryLoader_48,this._Compiler_17,this._ROUTES_41,this._ROUTER_CONFIGURATION_43)); }
    return this.__Router_49;
  }
  get _ActivatedRoute_50():any {
    if ((this.__ActivatedRoute_50 == (null as any))) { (this.__ActivatedRoute_50 = import8.rootRoute(this._Router_49)); }
    return this.__ActivatedRoute_50;
  }
  get _APP_BOOTSTRAP_LISTENER_51():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_51 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_51 = [import8.initialRouterNavigation(this._Router_49,this._ROUTER_CONFIGURATION_43)]); }
    return this.__APP_BOOTSTRAP_LISTENER_51;
  }
  get _TRANSLATIONS_FORMAT_52():any {
    if ((this.__TRANSLATIONS_FORMAT_52 == (null as any))) { (this.__TRANSLATIONS_FORMAT_52 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_52;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._ROUTER_FORROOT_GUARD_6 = import8.provideForRootGuard(this.parent.get(import51.Router,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_6);
    this._FlugModule_8 = new import9.FlugModule();
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import4.errorHandler();
    this._ApplicationInitStatus_13 = new import11.ApplicationInitStatus(this.parent.get(import11.APP_INITIALIZER,(null as any)));
    this._Testability_14 = new import12.Testability(this.parent.get(import42.NgZone));
    this._ApplicationRef__15 = new import13.ApplicationRef_(this.parent.get(import42.NgZone),this.parent.get(import52.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_13,this.parent.get(import12.TestabilityRegistry,(null as any)),this._Testability_14);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import9.FlugModule)) { return this._FlugModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import53.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import54.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import11.ApplicationInitStatus)) { return this._ApplicationInitStatus_13; }
    if ((token === import12.Testability)) { return this._Testability_14; }
    if ((token === import13.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import13.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import14.Compiler)) { return this._Compiler_17; }
    if ((token === import39.APP_ID)) { return this._APP_ID_18; }
    if ((token === import55.DOCUMENT)) { return this._DOCUMENT_19; }
    if ((token === import15.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import16.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import16.EventManager)) { return this._EventManager_22; }
    if ((token === import17.DomSharedStylesHost)) { return this._DomSharedStylesHost_23; }
    if ((token === import56.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_25; }
    if ((token === import57.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import19.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import58.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import20.ViewUtils)) { return this._ViewUtils_29; }
    if ((token === import59.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import60.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import17.SharedStylesHost)) { return this._SharedStylesHost_32; }
    if ((token === import21.Title)) { return this._Title_33; }
    if ((token === import22.BrowserXhr)) { return this._BrowserXhr_34; }
    if ((token === import23.ResponseOptions)) { return this._ResponseOptions_35; }
    if ((token === import61.XSRFStrategy)) { return this._XSRFStrategy_36; }
    if ((token === import24.XHRBackend)) { return this._XHRBackend_37; }
    if ((token === import25.RequestOptions)) { return this._RequestOptions_38; }
    if ((token === import62.Http)) { return this._Http_39; }
    if ((token === import26.RadioControlRegistry)) { return this._RadioControlRegistry_40; }
    if ((token === import63.ROUTES)) { return this._ROUTES_41; }
    if ((token === import27.FlugService)) { return this._FlugService_42; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_43; }
    if ((token === import50.LocationStrategy)) { return this._LocationStrategy_44; }
    if ((token === import28.Location)) { return this._Location_45; }
    if ((token === import29.UrlSerializer)) { return this._UrlSerializer_46; }
    if ((token === import30.RouterOutletMap)) { return this._RouterOutletMap_47; }
    if ((token === import64.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_48; }
    if ((token === import51.Router)) { return this._Router_49; }
    if ((token === import65.ActivatedRoute)) { return this._ActivatedRoute_50; }
    if ((token === import39.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_51; }
    if ((token === import66.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_52; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);