/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['input.ng-invalid[_ngcontent-%COMP%] {\r\n    border-left-color: deeppink;\r\n    border-left-style: solid;\r\n    border-left-width: 5px;\r\n}\r\n\r\ninput.ng-valid[_ngcontent-%COMP%] {\r\n    border-left-color: chartreuse;\r\n    border-left-style: solid;\r\n    border-left-width: 5px;\r\n}'];