/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/flug/flug-suchen/flug-suchen.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../app/flug/services/flug.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './flug-suchen.component.css.shim';
import * as import12 from '@angular/forms/src/directives/ng_form';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/validators';
import * as import16 from '../../../../app/validators/ort.validator.directive';
import * as import17 from '@angular/forms/src/directives/ng_model';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from '@angular/common/src/directives/ng_for';
import * as import20 from '@angular/common/src/pipes/date_pipe';
import * as import21 from '../../../../app/pipes/city.pipe';
import * as import22 from '@angular/common/src/pipes/json_pipe';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import26 from '@angular/core/src/i18n/tokens';
import * as import27 from '@angular/forms/src/validators';
import * as import28 from '@angular/forms/src/directives/control_value_accessor';
import * as import29 from '@angular/forms/src/directives/ng_control';
import * as import30 from '@angular/forms/src/directives/control_container';
import * as import31 from '@angular/router/src/directives/router_link';
import * as import32 from '@angular/router/src/router';
import * as import33 from '@angular/router/src/router_state';
import * as import34 from '@angular/common/src/location/location_strategy';
import * as import35 from '@angular/core/src/security';
var renderType_FlugSuchenComponent_Host:import0.RenderComponentType = (null as any);
class _View_FlugSuchenComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FlugSuchenComponent_0_4:import3.FlugSuchenComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent_Host0,renderType_FlugSuchenComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('flug-suchen',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FlugSuchenComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FlugSuchenComponent_0_4 = new import3.FlugSuchenComponent(this.parentInjector.get(import8.FlugService));
    this._appEl_0.initComponent(this._FlugSuchenComponent_0_4,[],compView_0);
    compView_0.create(this._FlugSuchenComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FlugSuchenComponent) && (0 === requestNodeIndex))) { return this._FlugSuchenComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FlugSuchenComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_FlugSuchenComponent_Host === (null as any))) { (renderType_FlugSuchenComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_FlugSuchenComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const FlugSuchenComponentNgFactory:import10.ComponentFactory<import3.FlugSuchenComponent> = new import10.ComponentFactory<import3.FlugSuchenComponent>('flug-suchen',viewFactory_FlugSuchenComponent_Host0,import3.FlugSuchenComponent);
const styles_FlugSuchenComponent:any[] = [import11.styles];
var renderType_FlugSuchenComponent:import0.RenderComponentType = (null as any);
class _View_FlugSuchenComponent0 extends import1.AppView<import3.FlugSuchenComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _NgForm_3_3:import12.NgForm;
  _ControlContainer_3_4:any;
  _NgControlStatusGroup_3_5:import13.NgControlStatusGroup;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import14.DefaultValueAccessor;
  _RequiredValidator_10_4:import15.RequiredValidator;
  _MinLengthValidator_10_5:import15.MinLengthValidator;
  _MaxLengthValidator_10_6:import15.MaxLengthValidator;
  _PatternValidator_10_7:import15.PatternValidator;
  _OrtValidatorDirective_10_8:import16.OrtValidatorDirective;
  _NG_VALIDATORS_10_9:any[];
  _NG_VALUE_ACCESSOR_10_10:any[];
  _NgModel_10_11:import17.NgModel;
  _NgControl_10_12:any;
  _NgControlStatus_10_13:import13.NgControlStatus;
  _text_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import18.NgIf;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import18.NgIf;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import18.NgIf;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import18.NgIf;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import18.NgIf;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import18.NgIf;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import18.NgIf;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import18.NgIf;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_34_4:any[];
  _NgModel_34_5:import17.NgModel;
  _NgControl_34_6:any;
  _NgControlStatus_34_7:import13.NgControlStatus;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _anchor_46:any;
  /*private*/ _appEl_46:import2.AppElement;
  _TemplateRef_46_5:any;
  _NgFor_46_6:import19.NgFor;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  _pipe_date_0:import20.DatePipe;
  _pipe_city_1:import21.CityPipe;
  _pipe_json_2:import22.JsonPipe;
  /*private*/ _expr_50:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent0,renderType_FlugSuchenComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Flug suchen!!!',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this._NgForm_3_3 = new import12.NgForm((null as any),(null as any));
    this._ControlContainer_3_4 = this._NgForm_3_3;
    this._NgControlStatusGroup_3_5 = new import13.NgControlStatusGroup(this._ControlContainer_3_4);
    this._text_4 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','form-group');
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'label',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Von:',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'input',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','form-control');
    this.renderer.setElementAttribute(this._el_10,'maxlength','30');
    this.renderer.setElementAttribute(this._el_10,'minlength','3');
    this.renderer.setElementAttribute(this._el_10,'name','von');
    this.renderer.setElementAttribute(this._el_10,'ort','Graz,München,Hamburg,Frankfurt,Zürich,Wien');
    this.renderer.setElementAttribute(this._el_10,'pattern','^\\w+$');
    this.renderer.setElementAttribute(this._el_10,'required','');
    this.renderer.setElementAttribute(this._el_10,'xortAsync','');
    this._DefaultValueAccessor_10_3 = new import14.DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_10));
    this._RequiredValidator_10_4 = new import15.RequiredValidator();
    this._MinLengthValidator_10_5 = new import15.MinLengthValidator();
    this._MaxLengthValidator_10_6 = new import15.MaxLengthValidator();
    this._PatternValidator_10_7 = new import15.PatternValidator();
    this._OrtValidatorDirective_10_8 = new import16.OrtValidatorDirective();
    this._NG_VALIDATORS_10_9 = [
      this._RequiredValidator_10_4,
      this._MinLengthValidator_10_5,
      this._MaxLengthValidator_10_6,
      this._PatternValidator_10_7,
      this._OrtValidatorDirective_10_8
    ]
    ;
    this._NG_VALUE_ACCESSOR_10_10 = [this._DefaultValueAccessor_10_3];
    this._NgModel_10_11 = new import17.NgModel(this._ControlContainer_3_4,this._NG_VALIDATORS_10_9,(null as any),this._NG_VALUE_ACCESSOR_10_10);
    this._NgControl_10_12 = this._NgModel_10_11;
    this._NgControlStatus_10_13 = new import13.NgControlStatus(this._NgControl_10_12);
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_13 = new import2.AppElement(13,3,this,this._anchor_13);
    this._TemplateRef_13_5 = new import24.TemplateRef_(this._appEl_13,viewFactory_FlugSuchenComponent1);
    this._NgIf_13_6 = new import18.NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_15 = new import2.AppElement(15,3,this,this._anchor_15);
    this._TemplateRef_15_5 = new import24.TemplateRef_(this._appEl_15,viewFactory_FlugSuchenComponent2);
    this._NgIf_15_6 = new import18.NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_17 = new import2.AppElement(17,3,this,this._anchor_17);
    this._TemplateRef_17_5 = new import24.TemplateRef_(this._appEl_17,viewFactory_FlugSuchenComponent3);
    this._NgIf_17_6 = new import18.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_19 = new import2.AppElement(19,3,this,this._anchor_19);
    this._TemplateRef_19_5 = new import24.TemplateRef_(this._appEl_19,viewFactory_FlugSuchenComponent4);
    this._NgIf_19_6 = new import18.NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_21 = new import2.AppElement(21,3,this,this._anchor_21);
    this._TemplateRef_21_5 = new import24.TemplateRef_(this._appEl_21,viewFactory_FlugSuchenComponent5);
    this._NgIf_21_6 = new import18.NgIf(this._appEl_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_23 = new import2.AppElement(23,3,this,this._anchor_23);
    this._TemplateRef_23_5 = new import24.TemplateRef_(this._appEl_23,viewFactory_FlugSuchenComponent6);
    this._NgIf_23_6 = new import18.NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_25 = new import2.AppElement(25,3,this,this._anchor_25);
    this._TemplateRef_25_5 = new import24.TemplateRef_(this._appEl_25,viewFactory_FlugSuchenComponent7);
    this._NgIf_25_6 = new import18.NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_27 = new import2.AppElement(27,3,this,this._anchor_27);
    this._TemplateRef_27_5 = new import24.TemplateRef_(this._appEl_27,viewFactory_FlugSuchenComponent8);
    this._NgIf_27_6 = new import18.NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-group');
    this._text_30 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'label',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Nach:',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_29,'input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','form-control');
    this.renderer.setElementAttribute(this._el_34,'name','nach');
    this._DefaultValueAccessor_34_3 = new import14.DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_34));
    this._NG_VALUE_ACCESSOR_34_4 = [this._DefaultValueAccessor_34_3];
    this._NgModel_34_5 = new import17.NgModel(this._ControlContainer_3_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_4);
    this._NgControl_34_6 = this._NgModel_34_5;
    this._NgControlStatus_34_7 = new import13.NgControlStatus(this._NgControl_34_6);
    this._text_35 = this.renderer.createText(this._el_29,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','form-group');
    this._text_38 = this.renderer.createText(this._el_37,'\n\n        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','btn btn-primary');
    this._text_40 = this.renderer.createText(this._el_39,'\n            Suchen!\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_3,'table',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','table table-striped');
    this._text_44 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'tbody',(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_45,(null as any));
    this._appEl_46 = new import2.AppElement(46,45,this,this._anchor_46);
    this._TemplateRef_46_5 = new import24.TemplateRef_(this._appEl_46,viewFactory_FlugSuchenComponent9);
    this._NgFor_46_6 = new import19.NgFor(this._appEl_46.vcRef,this._TemplateRef_46_5,this.parentInjector.get(import25.IterableDiffers),this.ref);
    this._text_47 = this.renderer.createText(this._el_45,'\n    ',(null as any));
    this._text_48 = this.renderer.createText(this._el_3,'\n\n',(null as any));
    this._text_49 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_50 = this.renderer.createElement(parentRenderNode,'pre',(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'submit',this.eventHandler(this._handle_submit_3_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_3,'reset',this.eventHandler(this._handle_reset_3_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_10,'ngModelChange',this.eventHandler(this._handle_ngModelChange_10_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_10,'input',this.eventHandler(this._handle_input_10_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_10,'blur',this.eventHandler(this._handle_blur_10_2.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_10_11.update.subscribe(this.eventHandler(this._handle_ngModelChange_10_0.bind(this)));
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_34,'ngModelChange',this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_34,'input',this.eventHandler(this._handle_input_34_1.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_34,'blur',this.eventHandler(this._handle_blur_34_2.bind(this)));
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_34_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    this._expr_49 = import7.UNINITIALIZED;
    this._pipe_date_0 = new import20.DatePipe(this.parentInjector.get(import26.LOCALE_ID));
    this._pipe_city_1 = new import21.CityPipe();
    this._pipe_json_2 = new import22.JsonPipe();
    this._expr_50 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._anchor_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3; }
    if (((token === import15.RequiredValidator) && (10 === requestNodeIndex))) { return this._RequiredValidator_10_4; }
    if (((token === import15.MinLengthValidator) && (10 === requestNodeIndex))) { return this._MinLengthValidator_10_5; }
    if (((token === import15.MaxLengthValidator) && (10 === requestNodeIndex))) { return this._MaxLengthValidator_10_6; }
    if (((token === import15.PatternValidator) && (10 === requestNodeIndex))) { return this._PatternValidator_10_7; }
    if (((token === import16.OrtValidatorDirective) && (10 === requestNodeIndex))) { return this._OrtValidatorDirective_10_8; }
    if (((token === import27.NG_VALIDATORS) && (10 === requestNodeIndex))) { return this._NG_VALIDATORS_10_9; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_10; }
    if (((token === import17.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_11; }
    if (((token === import29.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_12; }
    if (((token === import13.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_13; }
    if (((token === import24.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import18.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6; }
    if (((token === import24.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import18.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6; }
    if (((token === import24.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import18.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    if (((token === import24.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import18.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6; }
    if (((token === import24.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import18.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6; }
    if (((token === import24.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import18.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6; }
    if (((token === import24.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import18.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6; }
    if (((token === import24.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import18.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6; }
    if (((token === import14.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_4; }
    if (((token === import17.NgModel) && (34 === requestNodeIndex))) { return this._NgModel_34_5; }
    if (((token === import29.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_6; }
    if (((token === import13.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_7; }
    if (((token === import24.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import19.NgFor) && (46 === requestNodeIndex))) { return this._NgFor_46_6; }
    if (((token === import12.NgForm) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NgForm_3_3; }
    if (((token === import30.ControlContainer) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._ControlContainer_3_4; }
    if (((token === import13.NgControlStatusGroup) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NgControlStatusGroup_3_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_11:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._RequiredValidator_10_4.required = currVal_11;
      this._expr_11 = currVal_11;
    }
    changes = (null as any);
    const currVal_13:any = '3';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._MinLengthValidator_10_5.minlength = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['minlength'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._MinLengthValidator_10_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_15:any = '30';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._MaxLengthValidator_10_6.maxlength = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['maxlength'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._MaxLengthValidator_10_6.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_17:any = '^\\w+$';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._PatternValidator_10_7.pattern = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['pattern'] = new import7.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._PatternValidator_10_7.ngOnChanges(changes); }
    const currVal_19:any = 'Graz,München,Hamburg,Frankfurt,Zürich,Wien';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._OrtValidatorDirective_10_8.ort = currVal_19;
      this._expr_19 = currVal_19;
    }
    changes = (null as any);
    const currVal_20:any = 'von';
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._NgModel_10_11.name = currVal_20;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_20,currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this.context.von;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._NgModel_10_11.model = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._NgModel_10_11.ngOnChanges(changes); }
    const currVal_28:boolean = !((this._NgForm_3_3 == (null as any))? (null as any): ((this._NgForm_3_3.controls['von'] == (null as any))? (null as any): this._NgForm_3_3.controls['von'].valid));
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._NgIf_13_6.ngIf = currVal_28;
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = ((this._NgForm_3_3 == (null as any))? (null as any): ((this._NgForm_3_3.controls['von'] == (null as any))? (null as any): this._NgForm_3_3.controls['von'].hasError('required')));
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._NgIf_15_6.ngIf = currVal_29;
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = ((this._NgForm_3_3 == (null as any))? (null as any): ((this._NgForm_3_3.controls['von'] == (null as any))? (null as any): this._NgForm_3_3.controls['von'].hasError('minlength')));
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._NgIf_17_6.ngIf = currVal_30;
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = ((this._NgForm_3_3 == (null as any))? (null as any): ((this._NgForm_3_3.controls['von'] == (null as any))? (null as any): this._NgForm_3_3.controls['von'].hasError('maxlength')));
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._NgIf_19_6.ngIf = currVal_31;
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = ((this._NgForm_3_3 == (null as any))? (null as any): ((this._NgForm_3_3.controls['von'] == (null as any))? (null as any): this._NgForm_3_3.controls['von'].hasError('pattern')));
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._NgIf_21_6.ngIf = currVal_32;
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = ((this._NgForm_3_3 == (null as any))? (null as any): ((this._NgForm_3_3.controls['von'] == (null as any))? (null as any): this._NgForm_3_3.controls['von'].hasError('ort')));
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._NgIf_23_6.ngIf = currVal_33;
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = ((this._NgForm_3_3 == (null as any))? (null as any): ((this._NgForm_3_3.controls['von'] == (null as any))? (null as any): this._NgForm_3_3.controls['von'].hasError('ortAsync')));
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._NgIf_25_6.ngIf = currVal_34;
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = ((this._NgForm_3_3 == (null as any))? (null as any): ((this._NgForm_3_3.controls['von'] == (null as any))? (null as any): this._NgForm_3_3.controls['von'].pending));
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._NgIf_27_6.ngIf = currVal_35;
      this._expr_35 = currVal_35;
    }
    changes = (null as any);
    const currVal_39:any = 'nach';
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this._NgModel_34_5.name = currVal_39;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_39,currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this.context.nach;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this._NgModel_34_5.model = currVal_40;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_40,currVal_40);
      this._expr_40 = currVal_40;
    }
    if ((changes !== (null as any))) { this._NgModel_34_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_49:any = this.context.fluege;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this._NgFor_46_6.ngForOf = currVal_49;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_49,currVal_49);
      this._expr_49 = currVal_49;
    }
    if ((changes !== (null as any))) { this._NgFor_46_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_46_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._NgControlStatusGroup_3_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'ng-untouched',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._NgControlStatusGroup_3_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_3,'ng-touched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_3_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_3,'ng-pristine',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_3_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_3,'ng-dirty',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_3_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_3,'ng-valid',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_3_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_3,'ng-invalid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_12:any = (this._RequiredValidator_10_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementAttribute(this._el_10,'required',((currVal_12 == (null as any))? (null as any): currVal_12.toString()));
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = (this._MinLengthValidator_10_5.minlength? this._MinLengthValidator_10_5.minlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementAttribute(this._el_10,'minlength',((currVal_14 == (null as any))? (null as any): currVal_14.toString()));
      this._expr_14 = currVal_14;
    }
    const currVal_16:any = (this._MaxLengthValidator_10_6.maxlength? this._MaxLengthValidator_10_6.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementAttribute(this._el_10,'maxlength',((currVal_16 == (null as any))? (null as any): currVal_16.toString()));
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = (this._PatternValidator_10_7.pattern? this._PatternValidator_10_7.pattern: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementAttribute(this._el_10,'pattern',((currVal_18 == (null as any))? (null as any): currVal_18.toString()));
      this._expr_18 = currVal_18;
    }
    const currVal_22:any = this._NgControlStatus_10_13.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_10,'ng-untouched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_10_13.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_10,'ng-touched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_10_13.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_10,'ng-pristine',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_10_13.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_10,'ng-dirty',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_10_13.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_10,'ng-valid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_10_13.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_10,'ng-invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_41:any = this._NgControlStatus_34_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_34_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_34_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_34_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_34_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_34_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_48:boolean = (!this.context.von || !this.context.nach);
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementProperty(this._el_39,'disabled',currVal_48);
      this._expr_48 = currVal_48;
    }
    valUnwrapper.reset();
    const currVal_50:any = import4.interpolate(1,'Warenkorb\n----------------------\n',valUnwrapper.unwrap(this._pipe_json_2.transform(this.context.selectedFlug)),'\n');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_50,currVal_50))) {
      this.renderer.setText(this._text_51,currVal_50);
      this._expr_50 = currVal_50;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_10_11.ngOnDestroy();
    this._NgModel_34_5.ngOnDestroy();
  }
  private _handle_submit_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_3_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_3_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_3_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.von = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_10_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_10_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.nach = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_34_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_34_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.suchen()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_FlugSuchenComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.FlugSuchenComponent> {
  if ((renderType_FlugSuchenComponent === (null as any))) { (renderType_FlugSuchenComponent = viewUtils.createRenderComponentType('c:/Users/Manfred/Documents/beratung/angular2/src/rc5/aot/app/flug/flug-suchen/flug-suchen.component.html',0,import9.ViewEncapsulation.Emulated,styles_FlugSuchenComponent,{})); }
  return new _View_FlugSuchenComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent1,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Fehlerhafte Eingabe!\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_FlugSuchenComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent2,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Pflichtfeld!\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_FlugSuchenComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent3,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Muss min. 3 Zeichen haben!\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_FlugSuchenComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent4,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Darf max. 3 Zeichen haben!\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_FlugSuchenComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent5,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Nur Buchstaben erlaubt!\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_FlugSuchenComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent6,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Ort existiert nicht! (Mögliche Werte: Graz, Hamburg)\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_FlugSuchenComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent7,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Ort wird nicht angeflogen! (Mögliche Werte: Graz, Hamburg)\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_FlugSuchenComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent8,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'marquee',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            Validierung wird durchgeführt!\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_FlugSuchenComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_FlugSuchenComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import31.RouterLinkWithHref;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  _pipe_date_0_0:any;
  /*private*/ _expr_2:any;
  _pipe_city_1_0:any;
  /*private*/ _expr_3:any;
  _pipe_city_1_1:any;
  /*private*/ _expr_4:any;
  _arr_0:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FlugSuchenComponent9,renderType_FlugSuchenComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'a',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Auswählen',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,' |\n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_14,'a',(null as any));
    this._RouterLinkWithHref_19_3 = new import31.RouterLinkWithHref(this.parent.parentInjector.get(import32.Router),this.parent.parentInjector.get(import33.ActivatedRoute),this.parent.parentInjector.get(import34.LocationStrategy));
    this._text_20 = this.renderer.createText(this._el_19,'Edit',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._pipe_date_0_0 = import4.pureProxy2((<_View_FlugSuchenComponent0>this.parent)._pipe_date_0.transform.bind((<_View_FlugSuchenComponent0>this.parent)._pipe_date_0));
    this._expr_2 = import7.UNINITIALIZED;
    this._pipe_city_1_0 = import4.pureProxy1((<_View_FlugSuchenComponent0>this.parent)._pipe_city_1.transform.bind((<_View_FlugSuchenComponent0>this.parent)._pipe_city_1));
    this._expr_3 = import7.UNINITIALIZED;
    this._pipe_city_1_1 = import4.pureProxy1((<_View_FlugSuchenComponent0>this.parent)._pipe_city_1.transform.bind((<_View_FlugSuchenComponent0>this.parent)._pipe_city_1));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._arr_0 = import4.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const valUnwrapper:any = new import7.ValueUnwrapper();
    changes = (null as any);
    const currVal_7:any = this._arr_0('../flug-edit',this.context.$implicit.id);
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkWithHref_19_3.routerLink = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_19_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = (this.context.$implicit == this.parent.context.selectedFlug);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'active',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    valUnwrapper.reset();
    const currVal_2:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_0,(<_View_FlugSuchenComponent0>this.parent)._pipe_date_0.transform)(this.context.$implicit.datum,'dd.MM.yyyy')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_2,currVal_2))) {
      this.renderer.setText(this._text_6,currVal_2);
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_city_1_0,(<_View_FlugSuchenComponent0>this.parent)._pipe_city_1.transform)(this.context.$implicit.abflugort)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_9,currVal_3);
      this._expr_3 = currVal_3;
    }
    valUnwrapper.reset();
    const currVal_4:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_city_1_1,(<_View_FlugSuchenComponent0>this.parent)._pipe_city_1.transform)(this.context.$implicit.zielort)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_4,currVal_4))) {
      this.renderer.setText(this._text_12,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_8:any = this._RouterLinkWithHref_19_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_19,'href',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_19_3.ngOnDestroy();
  }
  private _handle_click_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.select(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_19_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_FlugSuchenComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FlugSuchenComponent9(viewUtils,parentInjector,declarationEl);
}